services:
  - type: web
    name: mtproto-proxy
    runtime: docker
    plan: free
    envVars:
      - key: SECRET
        generateValue: true
      - key: PORT
        value: "8443"
    ports:
      - port: 8443
        protocol: TCP
